#calculating demerit points
# Maryam Mohebi - mam3518@arastudent.ac.nz
# Stage 2

import os
from flask import Flask, render_template, request, flash

APPROVE_MSG = 'success'
DISAPPROVE_MSG = 'warning'
KEY_SIZE = 24
HTML_CODE = 'demerit_points_calculator.html'

#Creating the Flask instance by passing __name__
app = Flask(__name__)
app.debug = True
app.secret_key = os.urandom(KEY_SIZE)

@app.errorhandler(404)
def page_not_found(e):
    # if any other URL was entered, it will be handled with "404_with_timer.html" template
    # After 5 seconds the user will be redireted to the home page
    return render_template("404_with_timer.html")

def get_demerit_points(driving_speed, speed_limit, holiday_period = False):
    """This function display the output for calculating the demerit points. The mandatory penalty
        will return True if the points must be applied otherwise it returns False. The output format is tuple.
    """
    diff_speed = driving_speed - speed_limit
    if holiday_period == True:
        if driving_speed <= speed_limit:
            return False, 0
        elif diff_speed <= 4:
            return False, 10
        elif diff_speed > 4 and diff_speed <= 10:
            return True, 10
        elif diff_speed > 10 and diff_speed <= 20:
            return True, 20
        elif diff_speed > 20 and diff_speed <= 30:
            return True, 30
        else:
            return True, 50
    else:
        if driving_speed <= speed_limit:
            return False, 0
        elif diff_speed <= 5:
            return False, 10
        elif diff_speed >= 5 and diff_speed <= 10:
            return True, 10
        elif diff_speed > 10 and diff_speed <= 20:
            return True, 20
        elif diff_speed > 20 and diff_speed <= 30:
            return True, 30
        else:
            return True, 50
    
    



@app.route("/", methods = ['POST', 'GET'])

def home():
    """ Home page handler."""

    print(f'DEBUG. Function received http method type: {request.method}')

    if request.method == 'POST':
        # Using GET method to recieve the data that was sent by http post
        driving_speed = request.form.get('form_driving_speed')
        speed_limit = request.form.get('form_speed_limit')
        holiday_period = request.form.get('form_holiday_period')

        print('\nDEBUGGING')                               
        print(f'{holiday_period=}')
        # Look at the output generated by the above.
        # You need to pass True to the function if the value is on
        # You need to pass False to the function if the value is None        
        print('DEBUGGING\n')

        
        

        # Checking whether the driving speed and speed limit are entered
        if driving_speed != '' and speed_limit != '':
            if driving_speed.replace('.','').isdigit() and speed_limit.isdigit():


                #print('\nDEBUGGING')
                #output = get_demerit_points(float(driving_sp), int(driving_limit), holiday_box)

                # DB says
                # Please call the function once and make use of what it returns.
                # penalty_points = get_demerit_points(float(driving_speed), int(speed_limit), holiday_period)
                # penalty_type = get_demerit_points(float(driving_speed), int(speed_limit), holiday_period)
                penalty = get_demerit_points(float(driving_speed), int(speed_limit), holiday_period)
                
##                print(f'{driving_speed=}')
##                print(f'{speed_limit=}')
##                print(f'Penalty to be applied: {penalty_type[0]}')
##                print(f'Points to be applied: {penalty_points[1]}')
                mandatory_penalty_type = penalty[0]
                penalty_points = penalty[1]

                print('\nDEBUGGING')
                print(f'{driving_speed=}')
                print(f'{speed_limit=}')
                print(f'Mandatory penalty to be applied: {mandatory_penalty_type}')
                print(f'Points to be applied: {penalty_points}')
                print('DEBUGGING\n')
                
                # if penalty_type[0] == True:
                if mandatory_penalty_type == True:
                    print(f'The mandatory points to be applied: {penalty_points}.')
                else:
                    print(f'The discretional points to be applied: {penalty_points}.')

                # You are reinventing the purpose of the function again.  Don't.
##                if holiday_period == "on":
##                    if driving_speed <= speed_limit:
##                        flash(f'{driving_speed}km/h in a {speed_limit}km/h is not speeding.', APPROVE_MSG)
##                    elif penalty_type[0]:
##                        flash(f' The mandatory penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points[1]} points.', DISAPPROVE_MSG)
##                    else:
##                        flash(f'The discretional penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points[1]} points.', DISAPPROVE_MSG)
##                else:
##                     if driving_speed <= speed_limit:
##                        flash(f'{driving_speed}km/h in a {speed_limit}km/h is not speeding.', APPROVE_MSG)
##                     elif penalty_type[0]:
##                        flash(f' The mandatory penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points[1]} points.', DISAPPROVE_MSG)
##                     else:
##                        flash(f'The discretional penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points[1]} points.', DISAPPROVE_MSG)

                # Simplified version below
                if driving_speed <= speed_limit:
                    flash(f'{driving_speed}km/h in a {speed_limit}km/h is not speeding.', APPROVE_MSG)
                elif mandatory_penalty_type == True:
                    flash(f' The mandatory penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points} points.', DISAPPROVE_MSG)
                else:
                    flash(f'The discretional penalty for driving at {driving_speed}km/h in a {speed_limit}km/h zone is {penalty_points} points.', DISAPPROVE_MSG)
               


                        
        elif driving_speed == '' and speed_limit == '':
            # No numeric data was entered
            flash('Please enter a driving speed and speed limit.', DISAPPROVE_MSG)
        elif  driving_speed == '':
            flash('Please enter a driving speed.', DISAPPROVE_MSG)
        else:
            flash('Please enter a speed limit.', DISAPPROVE_MSG)
        #returning the HTML file
        return render_template (HTML_CODE, title='Demerit points calculator', form_driving_speed=driving_speed, form_speed_limit=speed_limit, form_holiday_period=holiday_period)
    else:
        return render_template(HTML_CODE, title = 'Demerit points calculator') 
    
if __name__== '__main__':
    app.run()
